### ISSUE TITLE
Problems With Go Modules

### ISSUE THREAD

**Issue by h4ckedneko** [essentialkaos/branca#12]
### Bug report

**System info:**

* **Version:** latest
* **OS (e.g. from `/etc/*-release`):** Solus
* **Kernel (`uname -a`):** Linux desktop-chan 5.6.19-159.current #1 SMP PREEMPT Fri Oct 16 17:49:06 UTC 2020 x86_64 GNU/Linux
* **Go version (`go version`):** go version go1.15.4 linux/amd64
* **Install tools:** go mod tidy

**Steps to reproduce:**

1. Import the package using `github.com/essentialkaos/branca`.
2. Run `go mod tidy`.

**Expected behavior:**

Everything should install.

**Actual behavior:**

Cannot install dependency `pkg.re/check.v1`.

**Additional info:**

These are the logs from `go mod tidy`.

```
go: finding module for package github.com/essentialkaos/branca
go: found github.com/essentialkaos/branca in github.com/essentialkaos/branca v1.3.0
go: finding module for package golang.org/x/crypto/chacha20poly1305
go: finding module for package pkg.re/check.v1
go: found golang.org/x/crypto/chacha20poly1305 in golang.org/x/crypto v0.0.0-20201016220609-9e8e0b390897
go: finding module for package pkg.re/check.v1
main imports
	github.com/essentialkaos/branca tested by
	github.com/essentialkaos/branca.test imports
	pkg.re/check.v1: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/h4ckedneko/.go/pkg/mod/cache/vcs/5a34ed54ed3cd750b349944fdc8bd0a4cd5d46a0754dbd413978f8364e2c27bf: exit status 128:
	error: RPC failed; HTTP 307 curl 22 The requested URL returned error: 307
	fatal: the remote end hung up unexpectedly
```

Apparently, packages from `pkg.re` cannot be discovered by the Go Modules Services.

I've created my temporary fork at [h4ckedneko/branca](https://github.com/h4ckedneko/branca) and changed the import URL of `go-check` then everything worked fine.

**Comment by andyone** [comment]
@h4ckedneko Hi!

Thanks for the detailed bug report! I have deployed the [new version](https://github.com/essentialkaos/pkgre/releases/tag/v4.0.0) of [pkg.re](https://pkg.re) service, and this problem should go away. Could you please check it?

**Comment by h4ckedneko** [comment]
It worked like a charm. Thank you very much!

**Comment by andyone** [comment]
Glad to hear that.
