### ISSUE TITLE
[Question]: Why no SetTTL method ?

### ISSUE THREAD

**Issue by sh0umik** [essentialkaos/branca#66]
### Question

Great library. I was using [the other one]([github.com/hako/branca](https://github.com/hako/branca)) for a while, but its not maintained anymore. Can not shift to this lib because of no SetTTL method ! Why is this missing ? Is this a design choice ? 

### Module version info

```shell
not using this yet, so ...
```

**Comment by andyone** [comment]
There is no need for such a method. TTL is not part of the token. The token contains a timestamp of its generation. You can check the expiration of the token using the [`IsExpired`](https://pkg.go.dev/github.com/essentialkaos/branca/v2#Token.IsExpired) method with your TTL.
